// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("Appointment")]
    public partial class Appointment
    {
        [Key]
        public int ID { get; set; }
        public int PatientID { get; set; }
        [Column(TypeName = "date")]
        public DateTime AppointmentDate { get; set; }
        public TimeSpan AppointmentTime { get; set; }
        public bool IsCanceled { get; set; }
        public bool IsRefunded { get; set; }
        public int DiscountPercentage { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? AppointmentEndDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateUpdated { get; set; }
        public Guid ConfirmationCode { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ConfirmationDate { get; set; }
        public bool? IsDoctorConfirmed { get; set; }
        public int ServiceClinicDoctorID { get; set; }
        public bool IsArchived { get; set; }
        [Column(TypeName = "money")]
        public decimal? PriceBeforeDiscount { get; set; }
        public bool IsPaid { get; set; }

        [ForeignKey("PatientID")]
        [InverseProperty("Appointments")]
        public virtual Patient Patient { get; set; }
        [ForeignKey("ServiceClinicDoctorID")]
        [InverseProperty("Appointments")]
        public virtual ServiceClinicDoctor ServiceClinicDoctor { get; set; }
        [InverseProperty("Appointment")]
        public virtual AppointmentProfile AppointmentProfile { get; set; }
    }
}