// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("AppointmentProfile")]
    [Index("AppointmentID", Name = "IX_AppointmentProfile", IsUnique = true)]
    public partial class AppointmentProfile
    {
        [Key]
        public int ID { get; set; }
        public int AppointmentID { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string PatientComments { get; set; }
        public string DoctorComments { get; set; }
        public bool IsResolved { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string AttachmentImageUrl { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string AttachmentDocUrl { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string AttachmentPdfUrl { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateUpdated { get; set; }
        public int? PatientRating { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string PatientReview { get; set; }
        public string QrCodeBase64 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? QrScannedDate { get; set; }
        public int? ClinicDiscountID { get; set; }

        [ForeignKey("AppointmentID")]
        [InverseProperty("AppointmentProfile")]
        public virtual Appointment Appointment { get; set; }
    }
}