// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("City")]
    [Index("Name", Name = "IX_City", IsUnique = true)]
    public partial class City
    {
        public City()
        {
            Patients = new HashSet<Patient>();
            Regions = new HashSet<Region>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public int CountryID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string NameUz { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string NameEn { get; set; }

        [ForeignKey("CountryID")]
        [InverseProperty("Cities")]
        public virtual Country Country { get; set; }
        [InverseProperty("City")]
        public virtual ICollection<Patient> Patients { get; set; }
        [InverseProperty("City")]
        public virtual ICollection<Region> Regions { get; set; }
    }
}