// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Index("ClinicID", "DoctorID", Name = "IX_ClinicDoctors", IsUnique = true)]
    public partial class ClinicDoctor
    {
        public ClinicDoctor()
        {
            ClinicDoctorEvents = new HashSet<ClinicDoctorEvent>();
            ClinicDoctorWorkDays = new HashSet<ClinicDoctorWorkDay>();
            PatientFavoriteDoctors = new HashSet<PatientFavoriteDoctor>();
            ServiceClinicDoctors = new HashSet<ServiceClinicDoctor>();
        }

        [Key]
        public int ID { get; set; }
        public int ClinicID { get; set; }
        public int DoctorID { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateDisabled { get; set; }

        [ForeignKey("ClinicID")]
        [InverseProperty("ClinicDoctors")]
        public virtual Clinic Clinic { get; set; }
        [ForeignKey("DoctorID")]
        [InverseProperty("ClinicDoctors")]
        public virtual Doctor Doctor { get; set; }
        [InverseProperty("ClinicDoctor")]
        public virtual ClinicDoctorAccount ClinicDoctorAccount { get; set; }
        [InverseProperty("ClinicDoctor")]
        public virtual ICollection<ClinicDoctorEvent> ClinicDoctorEvents { get; set; }
        [InverseProperty("ClinicDoctor")]
        public virtual ICollection<ClinicDoctorWorkDay> ClinicDoctorWorkDays { get; set; }
        [InverseProperty("ClinicDoctor")]
        public virtual ICollection<PatientFavoriteDoctor> PatientFavoriteDoctors { get; set; }
        [InverseProperty("ClinicDoctor")]
        public virtual ICollection<ServiceClinicDoctor> ServiceClinicDoctors { get; set; }
    }
}