// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("ClinicWorkDay")]
    [Index("ClinicID", "WeekDayID", Name = "IX_ClinicWorkDay", IsUnique = true)]
    public partial class ClinicWorkDay
    {
        [Key]
        public int ID { get; set; }
        public int WeekDayID { get; set; }
        public int ClinicID { get; set; }
        public TimeSpan OpenTime { get; set; }
        public TimeSpan CloseTime { get; set; }

        [ForeignKey("ClinicID")]
        [InverseProperty("ClinicWorkDays")]
        public virtual Clinic Clinic { get; set; }
        [ForeignKey("WeekDayID")]
        [InverseProperty("ClinicWorkDays")]
        public virtual WeekDay WeekDay { get; set; }
    }
}