// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("ClinicDiscount")]
    public partial class ClinicDiscount
    {
        [Key]
        public int ID { get; set; }
        [StringLength(500)]
        public string ImageUrl { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string Title { get; set; }
        [Required]
        [StringLength(2000)]
        public string Body { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal DiscountPercentage { get; set; }
        [Column(TypeName = "money")]
        public decimal PriceBeforeDiscount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndDate { get; set; }
        public bool IsActive { get; set; }
        public int ServiceClinicID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateUpdated { get; set; }
        public int SortOrder { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string TitleUz { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string TitleEn { get; set; }
        [StringLength(2000)]
        public string BodyUz { get; set; }
        [StringLength(2000)]
        [Unicode(false)]
        public string BodyEn { get; set; }

        [ForeignKey("ServiceClinicID")]
        [InverseProperty("ClinicDiscounts")]
        public virtual ServiceClinic ServiceClinic { get; set; }
    }
}