// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("ClinicGallery")]
    public partial class ClinicGallery
    {
        [Key]
        public int ID { get; set; }
        public int ClinicID { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Title { get; set; }
        [Required]
        [StringLength(500)]
        [Unicode(false)]
        public string ImageUrl { get; set; }
        public bool IsHidden { get; set; }
        public int SortOrder { get; set; }
        public bool IsThumbnail { get; set; }
        public bool IsMobileImage { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateUpdated { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string TitleUz { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string TitleEn { get; set; }

        [ForeignKey("ClinicID")]
        [InverseProperty("ClinicGalleries")]
        public virtual Clinic Clinic { get; set; }
    }
}