// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("ClinicDoctorEvent")]
    public partial class ClinicDoctorEvent
    {
        [Key]
        public int ID { get; set; }
        public int ClinicDoctorID { get; set; }
        [Required]
        [StringLength(250)]
        public string Title { get; set; }
        [StringLength(500)]
        public string Description { get; set; }
        [Column(TypeName = "date")]
        public DateTime AppointmentStartDate { get; set; }
        public TimeSpan AppointmentStartTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? AppointmentEndDate { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsCanceled { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateUpdated { get; set; }

        [ForeignKey("ClinicDoctorID")]
        [InverseProperty("ClinicDoctorEvents")]
        public virtual ClinicDoctor ClinicDoctor { get; set; }
    }
}