// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("ClinicReview")]
    public partial class ClinicReview
    {
        [Key]
        public int ID { get; set; }
        public int PatientID { get; set; }
        public int Rating { get; set; }
        [StringLength(100)]
        public string ReviewTitle { get; set; }
        [Required]
        [StringLength(1000)]
        public string Review { get; set; }
        public int ClinicID { get; set; }
        public bool IsDisabled { get; set; }
        public bool IsBlocked { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateUpdated { get; set; }
        public int? ReviewLanguage { get; set; }

        [ForeignKey("ClinicID")]
        [InverseProperty("ClinicReviews")]
        public virtual Clinic Clinic { get; set; }
        [ForeignKey("PatientID")]
        [InverseProperty("ClinicReviews")]
        public virtual Patient Patient { get; set; }
    }
}