// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("DoctorSpecialty")]
    [Index("DoctorID", "SpecialtyID", Name = "IX_DoctorSpecialty", IsUnique = true)]
    public partial class DoctorSpecialty
    {
        [Key]
        public int ID { get; set; }
        public int DoctorID { get; set; }
        public int SpecialtyID { get; set; }
        [Required]
        public bool? IsActive { get; set; }

        [ForeignKey("DoctorID")]
        [InverseProperty("DoctorSpecialties")]
        public virtual Doctor Doctor { get; set; }
        [ForeignKey("SpecialtyID")]
        [InverseProperty("DoctorSpecialties")]
        public virtual Specialty Specialty { get; set; }
    }
}