// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("DoctorProfile")]
    [Index("DoctorID", Name = "IX_DoctorProfile", IsUnique = true)]
    public partial class DoctorProfile
    {
        [Key]
        public int ID { get; set; }
        public int DoctorID { get; set; }
        public int PreferredLanguageID { get; set; }
        [Unicode(false)]
        public string About { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string ProfilePictureUrl { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string HomeAddress { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Street { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string District { get; set; }
        public int RegionID { get; set; }
        public bool IsMale { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string MedicalTitle { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string TaxpayerID { get; set; }
        [Unicode(false)]
        public string AboutUz { get; set; }
        [Unicode(false)]
        public string AboutEn { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string MedicalTitleUz { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string MedicalTitleEn { get; set; }

        [ForeignKey("DoctorID")]
        [InverseProperty("DoctorProfile")]
        public virtual Doctor Doctor { get; set; }
        [ForeignKey("RegionID")]
        [InverseProperty("DoctorProfiles")]
        public virtual Region Region { get; set; }
    }
}