// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    public partial class DoctorPhone
    {
        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string Phone { get; set; }
        [Required]
        public bool? IsMobile { get; set; }
        public bool IsPrimary { get; set; }
        public bool IsWorkPhone { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateUpdated { get; set; }
        public int DoctorID { get; set; }

        [ForeignKey("DoctorID")]
        [InverseProperty("DoctorPhones")]
        public virtual Doctor Doctor { get; set; }
    }
}