// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("Doctor")]
    public partial class Doctor
    {
        public Doctor()
        {
            ClinicDoctors = new HashSet<ClinicDoctor>();
            DoctorPhones = new HashSet<DoctorPhone>();
            DoctorSpecialties = new HashSet<DoctorSpecialty>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string LastName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string MiddleName { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Email { get; set; }
        [Column(TypeName = "date")]
        public DateTime DateOfBirth { get; set; }
        [Column(TypeName = "date")]
        public DateTime? RetirementDate { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        public bool IsRetired { get; set; }
        public bool IsFamilyDoctor { get; set; }
        [Column(TypeName = "date")]
        public DateTime? CareerStartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateUpdated { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string FirstNameUz { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string LastNameUz { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string MiddleNameUz { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string FirstNameEn { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string LastNameEn { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string MiddleNameEn { get; set; }

        [InverseProperty("Doctor")]
        public virtual DoctorProfile DoctorProfile { get; set; }
        [InverseProperty("Doctor")]
        public virtual ICollection<ClinicDoctor> ClinicDoctors { get; set; }
        [InverseProperty("Doctor")]
        public virtual ICollection<DoctorPhone> DoctorPhones { get; set; }
        [InverseProperty("Doctor")]
        public virtual ICollection<DoctorSpecialty> DoctorSpecialties { get; set; }
    }
}