// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    public partial class News
    {
        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string Title { get; set; }
        [Required]
        [Unicode(false)]
        public string Body { get; set; }
        public bool IsDisabled { get; set; }
        public bool IsFeatured { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateUpdated { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string BannerUrl { get; set; }
        public int? NewsLanguage { get; set; }
    }
}