// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Index("PatientID", "ClinicID", Name = "IX_PatientFavoriteClinics", IsUnique = true)]
    public partial class PatientFavoriteClinic
    {
        [Key]
        public int ID { get; set; }
        public int PatientID { get; set; }
        public int ClinicID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateUpdated { get; set; }
        public int SortOrder { get; set; }

        [ForeignKey("ClinicID")]
        [InverseProperty("PatientFavoriteClinics")]
        public virtual Clinic Clinic { get; set; }
        [ForeignKey("PatientID")]
        [InverseProperty("PatientFavoriteClinics")]
        public virtual Patient Patient { get; set; }
    }
}