// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("PatientProfile")]
    [Index("PatientID", Name = "IX_PatientProfile", IsUnique = true)]
    public partial class PatientProfile
    {
        [Key]
        public int ID { get; set; }
        public int PatientID { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DateOfBirth { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string Address { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Street { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string District { get; set; }
        public int? RegionID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateUpdated { get; set; }
        public bool IsMale { get; set; }
        public string PhotoBase64 { get; set; }

        [ForeignKey("PatientID")]
        [InverseProperty("PatientProfile")]
        public virtual Patient Patient { get; set; }
        [ForeignKey("RegionID")]
        [InverseProperty("PatientProfiles")]
        public virtual Region Region { get; set; }
    }
}