// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("Patient")]
    [Index("Phone", Name = "IX_Patient", IsUnique = true)]
    public partial class Patient
    {
        public Patient()
        {
            Appointments = new HashSet<Appointment>();
            ClinicReviews = new HashSet<ClinicReview>();
            PatientFavoriteClinics = new HashSet<PatientFavoriteClinic>();
            PatientFavoriteDoctors = new HashSet<PatientFavoriteDoctor>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string LastName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string MiddleName { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string Phone { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string SecondaryPhone { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Email { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateUpdated { get; set; }
        public bool IsActive { get; set; }
        public int PreferredLanguage { get; set; }
        public int? CityID { get; set; }

        [ForeignKey("CityID")]
        [InverseProperty("Patients")]
        public virtual City City { get; set; }
        [InverseProperty("Patient")]
        public virtual PatientAccount PatientAccount { get; set; }
        [InverseProperty("Patient")]
        public virtual PatientProfile PatientProfile { get; set; }
        [InverseProperty("Patient")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [InverseProperty("Patient")]
        public virtual ICollection<ClinicReview> ClinicReviews { get; set; }
        [InverseProperty("Patient")]
        public virtual ICollection<PatientFavoriteClinic> PatientFavoriteClinics { get; set; }
        [InverseProperty("Patient")]
        public virtual ICollection<PatientFavoriteDoctor> PatientFavoriteDoctors { get; set; }
    }
}