// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("PatientAccount")]
    [Index("PatientID", Name = "IX_PatientAccount", IsUnique = true)]
    [Index("MobilePhone", Name = "IX_PatientAccount_MobilePhone", IsUnique = true)]
    public partial class PatientAccount
    {
        [Key]
        public int ID { get; set; }
        public int PatientID { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string MobilePhone { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public bool IsPhoneVerified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateUpdated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastLoginDate { get; set; }
        public Guid UniqueKey { get; set; }
        public int? SmsActivationCode { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SmsActivationDate { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Email { get; set; }
        public bool IsEmailVerified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EmailVerificationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastVerificationAttemptDate { get; set; }

        [ForeignKey("PatientID")]
        [InverseProperty("PatientAccount")]
        public virtual Patient Patient { get; set; }
    }
}