// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("Region")]
    [Index("Name", "CityID", Name = "IX_Region", IsUnique = true)]
    public partial class Region
    {
        public Region()
        {
            Clinics = new HashSet<Clinic>();
            DoctorProfiles = new HashSet<DoctorProfile>();
            PatientProfiles = new HashSet<PatientProfile>();
            ZipCodes = new HashSet<ZipCode>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        public int CityID { get; set; }
        public int SortOrder { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string NameUz { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string NameEn { get; set; }

        [ForeignKey("CityID")]
        [InverseProperty("Regions")]
        public virtual City City { get; set; }
        [InverseProperty("Region")]
        public virtual ICollection<Clinic> Clinics { get; set; }
        [InverseProperty("Region")]
        public virtual ICollection<DoctorProfile> DoctorProfiles { get; set; }
        [InverseProperty("Region")]
        public virtual ICollection<PatientProfile> PatientProfiles { get; set; }
        [InverseProperty("Region")]
        public virtual ICollection<ZipCode> ZipCodes { get; set; }
    }
}