// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("Service")]
    [Index("Name", Name = "IX_Service", IsUnique = true)]
    public partial class Service
    {
        public Service()
        {
            ServiceClinics = new HashSet<ServiceClinic>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string Name { get; set; }
        [Unicode(false)]
        public string Description { get; set; }
        public int ServiceCategoryID { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        public int SortOrder { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string NameUz { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string NameEn { get; set; }
        [Unicode(false)]
        public string DescriptionUz { get; set; }
        [Unicode(false)]
        public string DescriptionEn { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string IconUrl { get; set; }

        [ForeignKey("ServiceCategoryID")]
        [InverseProperty("Services")]
        public virtual ServiceCategory ServiceCategory { get; set; }
        [InverseProperty("Service")]
        public virtual ICollection<ServiceClinic> ServiceClinics { get; set; }
    }
}