// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Index("ClinicDoctorID", "ServiceClinicID", Name = "IX_ServiceClinicDoctors", IsUnique = true)]
    public partial class ServiceClinicDoctor
    {
        public ServiceClinicDoctor()
        {
            Appointments = new HashSet<Appointment>();
        }

        [Key]
        public int ID { get; set; }
        public int ServiceClinicID { get; set; }
        public int ClinicDoctorID { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        [Column(TypeName = "time(0)")]
        public TimeSpan? AverageDuration { get; set; }
        [Column(TypeName = "money")]
        public decimal? Price { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string Description { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string DescriptionUz { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string DescriptionEn { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateUpdated { get; set; }

        [ForeignKey("ClinicDoctorID")]
        [InverseProperty("ServiceClinicDoctors")]
        public virtual ClinicDoctor ClinicDoctor { get; set; }
        [ForeignKey("ServiceClinicID")]
        [InverseProperty("ServiceClinicDoctors")]
        public virtual ServiceClinic ServiceClinic { get; set; }
        [InverseProperty("ServiceClinicDoctor")]
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}