// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("ServiceClinic")]
    [Index("ClinicID", "ServiceID", Name = "IX_ServiceClinic", IsUnique = true)]
    public partial class ServiceClinic
    {
        public ServiceClinic()
        {
            ClinicDiscounts = new HashSet<ClinicDiscount>();
            ServiceClinicDoctors = new HashSet<ServiceClinicDoctor>();
        }

        [Key]
        public int ID { get; set; }
        public int ClinicID { get; set; }
        public int ServiceID { get; set; }
        [Column(TypeName = "money")]
        public decimal? Price { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        [Column(TypeName = "time(0)")]
        public TimeSpan AverageDuration { get; set; }
        public int SortOrder { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateUpdated { get; set; }

        [ForeignKey("ServiceID")]
        [InverseProperty("ServiceClinics")]
        public virtual Service Service { get; set; }
        [InverseProperty("ServiceClinic")]
        public virtual ICollection<ClinicDiscount> ClinicDiscounts { get; set; }
        [InverseProperty("ServiceClinic")]
        public virtual ICollection<ServiceClinicDoctor> ServiceClinicDoctors { get; set; }
    }
}