// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("Specialty")]
    [Index("Name", Name = "IX_Specialty", IsUnique = true)]
    public partial class Specialty
    {
        public Specialty()
        {
            DoctorSpecialties = new HashSet<DoctorSpecialty>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string Name { get; set; }
        public int SortOrder { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string Description { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string NameUz { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string NameEn { get; set; }

        [InverseProperty("Specialty")]
        public virtual ICollection<DoctorSpecialty> DoctorSpecialties { get; set; }
    }
}