// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("Title")]
    [Index("Name", Name = "IX_Title", IsUnique = true)]
    public partial class Title
    {
        public Title()
        {
            ServiceCategories = new HashSet<ServiceCategory>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string Name { get; set; }
        public int SortOrder { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string NameUz { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string NameEn { get; set; }

        [InverseProperty("Title")]
        public virtual ICollection<ServiceCategory> ServiceCategories { get; set; }
    }
}