// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("WeekDay")]
    public partial class WeekDay
    {
        public WeekDay()
        {
            ClinicDoctorWorkDays = new HashSet<ClinicDoctorWorkDay>();
            ClinicWorkDays = new HashSet<ClinicWorkDay>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string NameUz { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string NameEn { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string ShortName { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string ShortNameUz { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string ShortNameEn { get; set; }

        [InverseProperty("WeekDay")]
        public virtual ICollection<ClinicDoctorWorkDay> ClinicDoctorWorkDays { get; set; }
        [InverseProperty("WeekDay")]
        public virtual ICollection<ClinicWorkDay> ClinicWorkDays { get; set; }
    }
}