// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GetWell.Data.Model
{
    [Table("ZipCode")]
    public partial class ZipCode
    {
        [Key]
        public int ID { get; set; }
        public double? Latitude { get; set; }
        public double? Longitude { get; set; }
        public int RegionID { get; set; }

        [ForeignKey("RegionID")]
        [InverseProperty("ZipCodes")]
        public virtual Region Region { get; set; }
    }
}